"""Categorize innspill markdown files by stakeholder type."""
import shutil
from pathlib import Path

MARKDOWN_DIR = Path(r"c:\Git\Digital-Forstelinje\background\helsereform-august\markdown")

CATEGORIES = {
    "1-virksomheter-i-helsesektoren":           "Virksomheter i helsesektoren",
    "2-direktorater-og-offentlige-virksomheter": "Direktorater og andre offentlige virksomheter",
    "3-undervisning-og-forskning":              "Undervisning og forskning",
    "4-helsepersonell":                         "Helsepersonell",
    "5-ideelle-organisasjoner":                 "Ideelle organisasjoner",
    "6-kommuner-og-kommunesektor":              "Kommuner og kommunesektor",
    "7-naringsliv-og-industri":                 "Næringsliv og industri",
}

# (filename, category_dir, organisation)
FILE_MAP = [
    # ── Virksomheter i helsesektoren ───────────────────────────────────────
    ("2026-01-Utfordringsbildet-psykisk-helse-og-rustjenester-innspillsnotat-til-Helsereformutvalget-15.01.26.md",
     "1-virksomheter-i-helsesektoren", "De regionale helseforetakene ved assisterende fagdirektører"),
    ("2026-02-Innspill-Helsereformutvalget.md",
     "1-virksomheter-i-helsesektoren", "Helse Nords brukerutvalg"),
    ("2026-03-Innspel-fra-Brukarutvala-i-Helse-Vest.md",
     "1-virksomheter-i-helsesektoren", "Brukarutvala Helse Vest"),
    ("2026-03-Innspill-til-Helsereformutvalget-fra-Stiftelsen-Renavangen.md",
     "1-virksomheter-i-helsesektoren", "Stiftelsen Renåvangen"),
    ("2026-03-Modell-for-Aktiv-Rehabilitering-innspill-til-Helsereformutvalget-2026.md",
     "1-virksomheter-i-helsesektoren", "Sunnasstiftelsen"),
    ("2026-04-260326-Helsereformutvalget-Innspill.md",
     "1-virksomheter-i-helsesektoren", "Oslo Universitetssykehus HF, prehospital klinikk"),
    ("2026-04-Helsereformutvalget-innspill-fra-Haugesund-Sanitetsforenings-revmatismesykehus.md",
     "1-virksomheter-i-helsesektoren", "Haugesund Sanitetsforening revmatismesykehus"),
    ("2026-04-Innspel-til-Helsereformutvalet-vedrorande.md",
     "1-virksomheter-i-helsesektoren", "Helseforetakene/direktørene i psykisk helsevern i Helse Vest"),
    ("2026-04-Innspel-til-helsereformutvalget-AiR.md",
     "1-virksomheter-i-helsesektoren", "AiR – Nordisk institutt for kurstedsstudier og rehabilitering"),
    ("2026-04-Innspill-til-Helsereformutvalget-fra-Meraker-kurbad-AS.md",
     "1-virksomheter-i-helsesektoren", "Meråker kurbad AS"),
    ("2026-04-Innspill-til-Heslereformutvalget-fra-UNN-ledelsen-april-2026.md",
     "1-virksomheter-i-helsesektoren", "Universitetssykehuset i Nord-Norge (UNN)"),
    ("2026-04-NKS-Kloverasen-Innspill.md",
     "1-virksomheter-i-helsesektoren", "NKS Kløveråsen"),
    ("2026-04-Til-Helsereformutvalget.md",
     "1-virksomheter-i-helsesektoren", "Diakonhjemmet sykehus (innspill 1)"),
    ("2026-05-Becker-rehabilitering-i-Norden-NSH-2026.md",
     "1-virksomheter-i-helsesektoren", "Sunnaas sykehus, vedlegg rehabilitering i Norden"),
    ("2026-05-Horingsinnspill-fra-Helsefellesskapet-sondre-Trondelag.md",
     "1-virksomheter-i-helsesektoren", "Helsefellesskapet Søndre Trøndelag"),
    ("2026-05-Koordineringsordninger-i-spesialisthelsetjenesten.md",
     "1-virksomheter-i-helsesektoren", "Regionale koordinerende enheter"),
    ("2026-05-Til-Helsereformutvalget.md",
     "1-virksomheter-i-helsesektoren", "Sunnaas sykehus"),
    ("2026-05-Uttale-Fremtidssikring-av-yngreomsorgen.md",
     "1-virksomheter-i-helsesektoren", "Helsefellesskapet Møre og Romsdal"),
    ("2026-06-15.06.2026-Brev-til-helsereformutvalget.md",
     "1-virksomheter-i-helsesektoren", "Diakonhjemmet sykehus (innspill 2)"),
    ("2026-06-Helsereformutvalget-innspill-fra-SamSar-prosjektet.md",
     "1-virksomheter-i-helsesektoren", "Sykehuset Innlandet (SamSar-prosjektet)"),
    ("2026-06-Innspel-til-Helsereformutvalget-fra-Helse-Bergen-HF.md",
     "1-virksomheter-i-helsesektoren", "Helse Bergen HF, forsknings- og utviklingsavdelinga"),
    ("2026-06-Innspill-Helsereformutvalget.md",
     "1-virksomheter-i-helsesektoren", "Helsefellesskapet Østfold"),
    ("2026-06-Innspill-til-HRU-fra-kommunenes-samhandlingsledere-i-nord.md",
     "1-virksomheter-i-helsesektoren", "Helsefellesskapene Nord-Norge"),
    ("2026-06-SamSar-lonner-det-seg-a-samarbeide.md",
     "1-virksomheter-i-helsesektoren", "Sykehuset Innlandet, vedlegg SamSar"),
    ("2026-06-Versjon-050226-Notat-om-finansielle-barrierer-samhandlingsmodell-DHO.md",
     "1-virksomheter-i-helsesektoren", "Helsefellesskapet i Bergensområdet – finansielle barrierer"),
    ("2026-06-Versjon-240426-Notat-om-organisatoriske-barrierer-Samhandlingsmodell-DHO.md",
     "1-virksomheter-i-helsesektoren", "Helsefellesskapet i Bergensområdet – samhandlingsmodell"),
    ("2026-06-Versjon-270326-Notat-om-teknologiske-barrierer-samhandlingsmodell-DHO.md",
     "1-virksomheter-i-helsesektoren", "Helsefellesskapet i Bergensområdet – teknologiske barrierer"),
    ("2026-07-2026-06-29-Innspill-fra-Strategisk-samarbeidsutvalg-Troms-og-Ofoten-til-Helsereformutvalget.md",
     "1-virksomheter-i-helsesektoren", "Strategisk samarbeidsutvalg Troms og Ofoten"),
    ("2026-07-Dagens-regelverk-har-behov-for-modernisering-innspill-til-Helsereformutvalget-.md",
     "1-virksomheter-i-helsesektoren", "Helse Sør-Øst RHF"),
    ("2026-08-Forskning-om-effektive-bygg.md",
     "1-virksomheter-i-helsesektoren", "Sykehusbygg"),

    # ── Direktorater og andre offentlige virksomheter ──────────────────────
    ("2026-01-2025-10-15-Innspill-til-Helsereformutvalget.md",
     "2-direktorater-og-offentlige-virksomheter", "Helsetilsynet"),
    ("2026-01-Om-behovet-for-reformer-i-helsesektoren-%E2%80%93-FHI.md",
     "2-direktorater-og-offentlige-virksomheter", "Folkehelseinstituttet (FHI) – innspill 1"),
    ("2026-02-Innspill-Helsereformutvalget_170226.md",
     "2-direktorater-og-offentlige-virksomheter", "Rådet for et aldersvennlig Norge"),
    ("2026-03-Folkehelseinstituttet.md",
     "2-direktorater-og-offentlige-virksomheter", "Folkehelseinstituttet (FHI) – innspill 2"),
    ("2026-05-Norsk-helsenett.md",
     "2-direktorater-og-offentlige-virksomheter", "Norsk helsenett"),
    ("2026-06-Innspill-til-Helsereformutvalget.md",
     "2-direktorater-og-offentlige-virksomheter", "Leverandørutviklingsprogrammet"),
    ("2026-07-Helsereformutvalget_horingsuttalelse_NSE.md",
     "2-direktorater-og-offentlige-virksomheter", "Nasjonalt senter for e-helseforskning"),
    ("2026-07-Innspill.md",
     "2-direktorater-og-offentlige-virksomheter", "Luftfartstilsynet"),

    # ── Undervisning og forskning ───────────────────────────────────────────
    ("2026-01-Innspill-fra-Nasjonalt-fagorgan-for-audiologi-og-optometri.md",
     "3-undervisning-og-forskning", "Nasjonalt fagorgan for audiologi og optometri – utfordringer"),
    ("2026-01-Innspill-Helsereformutvalget-Nasjonalt-senter-for-optikk-syn-og-oyehelse-USN.md",
     "3-undervisning-og-forskning", "Nasjonalt senter for optikk, syn og øyehelse (USN)"),
    ("2026-01-Nasjonalt-forskningsnettverk-for-palliasjon-i-primaerhelsetjenesten.md",
     "3-undervisning-og-forskning", "Nasjonalt forskningsnettverk for palliasjon i primærhelsetjenesten"),
    ("2026-01-Presentasjon-av-primaersykepleiemodell-som-struktur-og-organisering-av-pasientbehandling-i-Norge-Bard-Yngve-Gullvik-Nord-Universitet.md",
     "3-undervisning-og-forskning", "Bård Yngve Gullvik, Nord Universitet (privatperson/forsker)"),
    ("2026-02-Innspill-til-Helsereformutvalget-fra-de-medisinske-fakultetene.md",
     "3-undervisning-og-forskning", "De medisinske og helsevitenskapelige fakulteter"),
    ("2026-03-2026_innspill_helsereformutv_fagskolene.md",
     "3-undervisning-og-forskning", "HØY – Organisasjon for fagskole og høyere yrkesfaglig utdanning"),
    ("2026-03-Helhetlige_forslag_syn_og_horsel_Norge-innsendt.md",
     "3-undervisning-og-forskning", "Nasjonalt fagorgan for audiologi og optometri / Universitetet i Sørøst-Norge – løsninger"),
    ("2026-03-Innspill-til-Helsereformutvalget.md",
     "3-undervisning-og-forskning", "Universitetet i Oslo, Avdeling for allmennmedisin"),
    ("2026-03-Innspill-til-Helsereformutvalget-fra-HelseOmsorg21-radet.md",
     "3-undervisning-og-forskning", "HelseOmsorg21-rådet"),
    ("2026-03-Innspill-til-Helsereformutvalget-om-praksis-for-studenter-fra-FRONESIS_UiB-270226.md",
     "3-undervisning-og-forskning", "Universitetet i Bergen ved Eliassen, Hunskår og Tschudi Bondevik"),
    ("2026-04-2026-04-08-Helsereformutvalget-SINTEF-innspill-helseteknologi-og-innovasjon.md",
     "3-undervisning-og-forskning", "SINTEF – innspill helseteknologi og innovasjon (innspill 1)"),
    ("2026-05-2026-04-08-Helsereformutvalget-SINTEF-innspill-helseteknologi-og-innovasjon.md",
     "3-undervisning-og-forskning", "SINTEF – innspill helseteknologi og innovasjon (innspill 2)"),
    ("2026-05-Helhetlige_forslag_syn_og_horsel_Norge-innsendt.md",
     "3-undervisning-og-forskning", "Universitetet i Sørøst-Norge – løsninger syn og hørsel"),
    ("2026-05-Helsereformutvalget-NSDM-innspill-180526.md",
     "3-undervisning-og-forskning", "Nasjonalt senter for distriktsmedisin (NSDM)"),
    ("2026-05-KBT-Fagskole-AS-Innspill-til-helsereformutvalget.md",
     "3-undervisning-og-forskning", "KBT Fagskole AS"),
    ("2026-06-Til-Helsereformutvalget_innspill-fra-Oslo-Science-City_mai-2026.md",
     "3-undervisning-og-forskning", "Oslo Science City"),

    # ── Helsepersonell ─────────────────────────────────────────────────────
    ("2026-01-1-Rettslige-utfordringer-i-helseforetaksmodellen-Notat-til-HRU-121025-AK-Befring.md",
     "4-helsepersonell", "Anne Kjersti Befring (privatperson, juridisk ekspert)"),
    ("2026-01-2025.11.05-Psykologforenignens-innspill-om-utfordringer-til-helsereformutvalget.md",
     "4-helsepersonell", "Psykologforeningen – utfordringer"),
    ("2026-01-25.10.16-Innspill-til-Helsereformutvalget-Fagforbundet.md",
     "4-helsepersonell", "Fagforbundet"),
    ("2026-01-Innspill_helsereformutvalget2026_kiropraktorer.md",
     "4-helsepersonell", "Privatperson: Irgens med flere (kiropraktorer)"),
    ("2026-01-Innspill-fra-Arvid-Rongve-Helse-Fonna-og-UiB.md",
     "4-helsepersonell", "Privatperson: Arvid Rongve (Helse Fonna/UiB)"),
    ("2026-01-Innspill-om-utfordringer-til-Helsereformutvalget.md",
     "4-helsepersonell", "Terapeutikakomiteen"),
    ("2026-01-Innspill-til-Helsereformutvalget.md",
     "4-helsepersonell", "FO – Fellesorganisasjonen"),
    ("2026-01-Innspill-til-Helsereformutvalget-fra-Norsk-Ergoterapeutforbund-29.12.25.md",
     "4-helsepersonell", "Norsk ergoterapeutforbund"),
    ("2026-01-Innspill-utfordringsbildet-Helsereformutvalget.md",
     "4-helsepersonell", "Norges Optikerforbund – utfordringer"),
    ("2026-01-Norsk-Fysioterapeutforbunds-innspill-til-Helsereformutvalget_30.10.25.md",
     "4-helsepersonell", "Norsk fysioterapiforbund"),
    ("2026-01-NSF_Hva_er_problemet_i_norsk_helsetjeneste.md",
     "4-helsepersonell", "Norsk sykepleierforbund (NSF) – innspill 1"),
    ("2026-01-NTFs-innspill-til-Helsereformutvalget.md",
     "4-helsepersonell", "Den norske tannlegeforening (NTF)"),
    ("2026-01-Privatperson-Peter-Daniel-Aune-i-Levanger-kommune.md",
     "4-helsepersonell", "Privatperson: Peter Daniel Aune"),
    ("2026-01-Privatperson-Veronica-Berg-radiologi-HelseNord.md",
     "4-helsepersonell", "Privatperson: Veronica Berg (radiologi, Helse Nord)"),
    ("2026-01-Privatpersons-Kommentar-til-Helsereformutvalget-Jon-Einar-Nielsen.md",
     "4-helsepersonell", "Privatperson: Jon Einar Nielsen"),
    ("2026-02-Innspill-til-Helsereformutvalget_Kommuneoverlegeforum-Helgeland.md",
     "4-helsepersonell", "Kommuneoverlegeforum Helgeland"),
    ("2026-02-Legeforeningens-innspill-til-Helsereformutvalget-oktober-2025.md",
     "4-helsepersonell", "Legeforeningen – hovedinnspill"),
    ("2026-02-Psykologforeningen-innspill-8-etter-sentralstyremote.md",
     "4-helsepersonell", "Psykologforeningen – innspill modell"),
    ("2026-03-Brev_Helsereformkommisjonen_2026-Knut-Borch.md",
     "4-helsepersonell", "Privatperson: Knut Borch"),
    ("2026-03-Helsereformutvalget-innspill.md",
     "4-helsepersonell", "Privatperson/fastlege Halvorsen (innspill 2)"),
    ("2026-03-Innspill-helsereformutvalget.md",
     "4-helsepersonell", "Tannpleierforeningen"),
    ("2026-03-Innspill-losninger-Helsereformutvalget.md",
     "4-helsepersonell", "Norges Optikerforbund – løsninger"),
    ("2026-03-NOTAT-til-GB.md",
     "4-helsepersonell", "Privatperson: Rønneberg Hauge"),
    ("2026-03-NSF-Students-innspill-til-helsereformutvalget.md",
     "4-helsepersonell", "Norsk Sykepleierforbund Student"),
    ("2026-03-Styrket-organisering-av-FLO.md",
     "4-helsepersonell", "Privatperson/fastlege Halvorsen (innspill 1)"),
    ("2026-04-2026.04.07-Notat-til-Helsereformutvalget-om-psykiatri.md",
     "4-helsepersonell", "Saastad, Rosenqvist, Heier, Steen (privatpersoner, psykiatri)"),
    ("2026-04-Horingssvar-helsereformutvalget-220426.md",
     "4-helsepersonell", "Privatperson: Figenschou"),
    ("2026-04-Innspill-til-Helsereformutvalget-fra-Norsk-logopedforbund.md",
     "4-helsepersonell", "Norsk logopedforbund"),
    ("2026-04-Innspill-til-helsereformutvalget-fra-Norsk-Sykepleierforbund.md",
     "4-helsepersonell", "Norsk sykepleierforbund (NSF) – innspill 2"),
    ("2026-04-Jon-HovdaX.md",
     "4-helsepersonell", "Privatperson: Jon Hovda"),
    ("2026-04-Norsk-Radiografforbund_innspill-Helsereformutvalget_sign.md",
     "4-helsepersonell", "Norsk Radiografforbund"),
    ("2026-04-Til-Helsereformutvalget-ved-leder-Gunnar-Bovim-Bergen-.md",
     "4-helsepersonell", "Privatperson: Berge med flere"),
    ("2026-05-horing-helsereform.md",
     "4-helsepersonell", "Kommuneoverleger i Skien, Porsgrunn og Kragerø"),
    ("2026-05-Helsereformutvalget-Ungdomshelse-felles-innspill.md",
     "4-helsepersonell", "UngFunk, Barnesykepleierne, Norsk barnelegeforening, NBUPF, Helsesykepleierne NSF, Norsk forening for allmennmedisin"),
    ("2026-05-Horingsinnspill-til-Helsereformutvalget-fra-kommuneoverleger-i-Buskerud-og-Akershus.md",
     "4-helsepersonell", "Kommuneoverleger i Buskerud og Akershus"),
    ("2026-05-Innspill-til-Helsereformutvalget.md",
     "4-helsepersonell", "Privatperson: Resell"),
    ("2026-05-Kontoravtaler-mellom-kommunen-og-legekontoret.md",
     "4-helsepersonell", "Legeforeningen – notat om kontoravtaler"),
    ("2026-05-Legeforeningens-del-1.md",
     "4-helsepersonell", "Legeforeningen – innspill vedlegg del 1"),
    ("2026-05-Legeforeningen-Vedlegg-2.-Om-fastlegeordningen.md",
     "4-helsepersonell", "Legeforeningen – vedlegg 2: fastlegeordningen"),
    ("2026-05-Legeforeningen-Vedlegg-3.-Samhandling-i-helsetjenesten.md",
     "4-helsepersonell", "Legeforeningen – vedlegg 3: samhandling"),
    ("2026-05-Legeforeningen-Vedlegg-4.-Prinsipielle-avklaringer-knyttet-til-Prosjekt-X.md",
     "4-helsepersonell", "Legeforeningen – vedlegg 4: prinsipielle avklaringer"),
    ("2026-05-Vedlegg-1.-Det-regionale-nivaet-i-spesialisthjelsetjenesten.md",
     "4-helsepersonell", "Legeforeningen – vedlegg 1: det regionale nivå"),
    ("2026-06-brev-helseministerendelig.md",
     "4-helsepersonell", "Privatperson: Boye"),
    ("2026-06-Innspill-fra-NBUPF-til-Helsereformutvalget.md",
     "4-helsepersonell", "Norsk barne- og ungdomspsykiatrisk forening (NBUPF)"),
    ("2026-06-Psykologforeningen-om-helsereformutvalget-kortversjon-mai-2026-2.md",
     "4-helsepersonell", "Psykologforeningen – kortversjon"),
    ("2026-06-Til-Helsereformutvalget.md",
     "4-helsepersonell", "Privatperson: Folven"),
    ("2026-06-Vedlegg-1-Om-kommune-mai-2026.md",
     "4-helsepersonell", "Psykologforeningen – vedlegg 1: om kommune"),
    ("2026-06-Vedlegg-2-overganger-mai-2026.md",
     "4-helsepersonell", "Psykologforeningen – vedlegg 2: overganger"),
    ("2026-06-Vedlegg-3-Psykisk-helsevern-mai-2026.md",
     "4-helsepersonell", "Psykologforeningen – vedlegg 3: psykisk helsevern"),
    ("2026-06-Vedlegg-4-Tverrfaglig-spesialisert-rusbehandling-mai-2026.md",
     "4-helsepersonell", "Psykologforeningen – vedlegg 4: TSB"),
    ("2026-07-Helsereformutvalget.md",
     "4-helsepersonell", "Audiografforbundet"),
    ("2026-07-Helsereform-innspill.md",
     "4-helsepersonell", "Kommuneoverleger i Trøndelag"),
    ("2026-07-Innspill-til-Helserefomutvalget.md",
     "4-helsepersonell", "Ass. Kommuneoverlege Holmestrand"),
    ("2026-07-Skriftlig-innspill-til-Helsereformutvalget.md",
     "4-helsepersonell", "Norsk samfunnsmedisinsk forening"),
    ("2026-08-2026-07-03-Innspill-til-Helsereformutvalget-fra-Norsk-skadelegeforening.md",
     "4-helsepersonell", "Norsk skadelegeforening"),
    ("2026-01-2025-NITOs-innspill-Helsereformutvalgets-referansegruppe.md",
     "4-helsepersonell", "NITO"),

    # ── Ideelle organisasjoner ─────────────────────────────────────────────
    ("2026-01-Brukerrop.utfordringsbilde.HRFU_.md",
     "5-ideelle-organisasjoner", "Brukerrop"),
    ("2026-01-Hjerneradets-innspill-til-Helsereformutvalget.md",
     "5-ideelle-organisasjoner", "Hjernerådet"),
    ("2026-01-Hvorfor-trenger-vi-en-helsereform-i-Norge-LHL.md",
     "5-ideelle-organisasjoner", "LHL – innspill 1"),
    ("2026-01-Innspill-fra-Tyrili-til-Helsereformutvalget-04.12.2025.md",
     "5-ideelle-organisasjoner", "Tyrili"),
    ("2026-01-Innspill-Helsereformutvalget-NorVIS-2025.md",
     "5-ideelle-organisasjoner", "NorVis"),
    ("2026-01-Innspill-Helsereformutvalget-oktober-2025-Kreftforeningen.md",
     "5-ideelle-organisasjoner", "Kreftforeningen"),
    ("2026-01-Innspill-til-Helsereformutvalget_Nasjonalforeningen.md",
     "5-ideelle-organisasjoner", "Nasjonalforeningen for folkehelsen"),
    ("2026-01-Innspill-til-Helsreformutvalget-fra-FFO.md",
     "5-ideelle-organisasjoner", "FFO – innspill 1"),
    ("2026-01-Mental-Helse-Innspillsdokument-Helsereformutvalget-1.-desember-2025.md",
     "5-ideelle-organisasjoner", "Mental Helse"),
    ("2026-01-Parorendealliansen-Status-og-utfordringsbilder-parorende-Parorendealliansen-final.md",
     "5-ideelle-organisasjoner", "Pårørendealliansen – utfordringer"),
    ("2026-01-SAFO.md",
     "5-ideelle-organisasjoner", "SAFO"),
    ("2026-01-Unge-funksjonshemmede_Utfordringsbildet.md",
     "5-ideelle-organisasjoner", "Unge funksjonshemmede – utfordringer"),
    ("2026-02-Innspill-til-Helsereformutvalget-fra-Horselsforbundet-Oppdal-og-Rennebu_04.02.2026.md",
     "5-ideelle-organisasjoner", "Hørselsforbundet Oppdal og Rennebu"),
    ("2026-03-260313-Innspill-Helsereformutvalgets-arbeid-og-rehabilitering-13.3.2026.md",
     "5-ideelle-organisasjoner", "LHL – innspill 2 (rehabilitering)"),
    ("2026-03-2026-Innspill-Helsereformutvalget.md",
     "5-ideelle-organisasjoner", "Unge funksjonshemmede – løsninger"),
    ("2026-03-2026-innspill-til-Helsereformutvalget.md",
     "5-ideelle-organisasjoner", "Melanor"),
    ("2026-03-Felles-innspill-til-pagaende-utvalgsarbeid.md",
     "5-ideelle-organisasjoner", "UngFunk, FFO, Redd Barna, NFU, NORILCO, LDO, Psoriasis- og eksemforbundet Ung (felles)"),
    ("2026-03-Helsetjenesteaksjonen.md",
     "5-ideelle-organisasjoner", "Helsetjenesteaksjonen"),
    ("2026-03-Innspill-Helsereformutvalget-_-Verdighetsenteret.md",
     "5-ideelle-organisasjoner", "Verdighetssenteret"),
    ("2026-03-Til-Helsereformutvalget-fra-Hjernerystelsesforeningen.md",
     "5-ideelle-organisasjoner", "Hjernerystelsesforeningen"),
    ("2026-04-FFO.md",
     "5-ideelle-organisasjoner", "FFO – innspill 2 (20. april)"),
    ("2026-04-Helsereformutvalget-fra-PLTN.md",
     "5-ideelle-organisasjoner", "Personskadeforbundet (PLTN)"),
    ("2026-04-Horingsinnspill-fra-Ideellt-Nettverk.md",
     "5-ideelle-organisasjoner", "Ideelt nettverk"),
    ("2026-04-Innspill-Helsereformutvalget-brukerrop-april-2026.md",
     "5-ideelle-organisasjoner", "Leve (brukerorganisasjon for etterlatte ved selvmord)"),
    ("2026-04-Innspill-til-Helsereformutvalget-.md",
     "5-ideelle-organisasjoner", "Sanitetskvinnene"),
    ("2026-04-Innspill-til-helsereformutvalget-fra-nettverk-for-eldrefrivillighet.md",
     "5-ideelle-organisasjoner", "Nettverk for eldrefrivillighet / Sanitetskvinnene"),
    ("2026-04-Innspill-virksomheter-helsereformutvalget-%E2%80%93-Kopi.md",
     "5-ideelle-organisasjoner", "Sanitetskvinnene – innspill ideelle virksomheter"),
    ("2026-04-LIN_innspill-til-Helsereformutvalget.md",
     "5-ideelle-organisasjoner", "Likestilling, integrering nettverk (LIN)"),
    ("2026-05-Epilepsiforbundet-innspill-Helsereformutvalget-21.05.2026.md",
     "5-ideelle-organisasjoner", "Epilepsiforbundet"),
    ("2026-05-Innspill-helsereformutvalget.md",
     "5-ideelle-organisasjoner", "NORILCO"),
    ("2026-05-Ungfunk-modellvalg.md",
     "5-ideelle-organisasjoner", "UngFunk – modellvalg"),
    ("2026-06-Horingsinnspill-NOU-2026-Kommunekomm-del-1-PAA.md",
     "5-ideelle-organisasjoner", "Pårørendealliansen – vedlegg høringsinnspill kommunekommisjonen"),
    ("2026-06-Innspill-losninger-nasjonalt-parorende-Parorendealliansen.md",
     "5-ideelle-organisasjoner", "Pårørendealliansen – løsninger"),
    ("2026-06-Innspill-til-Helsereformutvalget-3.md",
     "5-ideelle-organisasjoner", "Nettverket av brukerrådledere – 21 helse- og velferdssentre i Trondheim"),

    # ── Kommuner og kommunesektor ───────────────────────────────────────────
    ("2026-01-2025-10-Notat-til-Helsereformutvalget-Kommunedirektorforum.md",
     "6-kommuner-og-kommunesektor", "Kommunedirektørforum"),
    ("2026-01-Innspill-til-Helsereformutvalget-utfordringsbildet-sett-fra-KS-10.2025.md",
     "6-kommuner-og-kommunesektor", "KS – innspill 1 (utfordringer)"),
    ("2026-02-Innspill-helsereforutvalg.-05.02.26.md",
     "6-kommuner-og-kommunesektor", "Steigen kommune ved kommuneoverlege Ingar Strand"),
    ("2026-02-Innspill-til-Helsereformutvalget-om-dagens-utfordringsbilde-fra-helseadministrasjonen-i-Drammen-kommune.md",
     "6-kommuner-og-kommunesektor", "Drammen kommune – innspill 1"),
    ("2026-03-Innspill-rusbehandlingsutvalget-rusbehandling-U18-25-ar.md",
     "6-kommuner-og-kommunesektor", "Trondheim kommune"),
    ("2026-03-Innspill-til-Helserefomrutvalget-fra-Den-offentlige-tannhelsetjenesten-i-Nordland.md",
     "6-kommuner-og-kommunesektor", "Nordland fylkeskommune"),
    ("2026-03-signert-innspill-til-helsereformutvalget-fra-snr.md",
     "6-kommuner-og-kommunesektor", "Samarbeidsrådet for Nedre Romerrike"),
    ("2026-03-Til-helsereformutvalget-KS-sitt-innspill-til-koordinering-samordning-og-utvikling-av-digitaliseringsarbeidet.md",
     "6-kommuner-og-kommunesektor", "KS – innspill digitalisering"),
    ("2026-04-2026-04-innspill-til-helsereformutvalget-Norsk-Kommunedirektorforum.md",
     "6-kommuner-og-kommunesektor", "Norsk kommunedirektørforum – modellutvikling"),
    ("2026-04-26-04-08-kriterier-til-helsereformutvalget.md",
     "6-kommuner-og-kommunesektor", "Norsk kommunedirektørforum – kriterier"),
    ("2026-04-Den-biopsykososiale-modell-og-grunnlag-for-en-helsereform.md",
     "6-kommuner-og-kommunesektor", "Lunner kommune ved kommuneoverlege Oure"),
    ("2026-04-Innspill-til-helsereformutvalget-2026-fra-Al-kommune.md",
     "6-kommuner-og-kommunesektor", "Ål kommune ved kommuneoverlege Strømmen"),
    ("2026-04-Innspill-til-KS-angaende-Helsereformutvalget.md",
     "6-kommuner-og-kommunesektor", "Kommunene i Midt-Troms"),
    ("2026-05-493286_1_1.md",
     "6-kommuner-og-kommunesektor", "Finnmark fylkeskommune"),
    ("2026-05-667211_1_1.md",
     "6-kommuner-og-kommunesektor", "Fylkesordfører/rådlederkollegiet"),
    ("2026-05-Horingsinnspill-til-Helsereformutvalget-fra-kommuneoverleger-i-Buskerud-og-Akershus.md",
     "6-kommuner-og-kommunesektor", "Kommuneoverleger i Buskerud og Akershus"),
    ("2026-05-Innspel-helsereformutvalet_Sunnmore-regionrad.md",
     "6-kommuner-og-kommunesektor", "Sunnmøre regionråd"),
    ("2026-05-Innspill-til-helsereformutvalget-fra-tannhelse-i-Telemark-fylkeskommune.md",
     "6-kommuner-og-kommunesektor", "Telemark fylkeskommune"),
    ("2026-06-2026-06-16-Til-Helsereformutvalget-innspill-til-utvalgets-arbeid-fra-Gardermoregionen-interkommunalt-politisk-rad.md",
     "6-kommuner-og-kommunesektor", "Gardermoregionen interkommunalt politisk råd"),
    ("2026-06-Helsereformen-faktaark-mai-2026.md",
     "6-kommuner-og-kommunesektor", "Region Kristiansand IPR"),
    ("2026-06-innspillHelsereformutvalget2026.md",
     "6-kommuner-og-kommunesektor", "Kommuneoverleger i Indre Namdal og Nærøysund og Midtre Namdal"),
    ("2026-06-KS-innspill-til-arbeidet-med-helsereformen-22.06.2026.md",
     "6-kommuner-og-kommunesektor", "KS – innspill 22.06.2026"),
    ("2026-06-Til-Helsereformutvalget-07.06.2026.md",
     "6-kommuner-og-kommunesektor", "Drammen kommune – innspill 2"),
    ("2026-06-Troms-fylkeskommune-Innspill-til-Helsereformutvalget26_06946-5-Vedtak-815055_4_1.md",
     "6-kommuner-og-kommunesektor", "Troms fylkeskommune"),
    ("2026-07-690416_1_1.md",
     "6-kommuner-og-kommunesektor", "KS storbynettverk"),
    ("2026-07-Innspill-til-Helserefomutvalget.md",
     "6-kommuner-og-kommunesektor", "Ass. Kommuneoverlege Holmestrand"),
    ("2026-07-Innspill-til-helsereformutvalget.md",
     "6-kommuner-og-kommunesektor", "Sør-Varanger kommune"),

    # ── Næringsliv og industri ──────────────────────────────────────────────
    ("2026-01-20251113-Teknas-forste-innspill-til-Helsereformutvalget.md",
     "7-naringsliv-og-industri", "Tekna"),
    ("2026-01-20260115-LMI-innspill-problembeskrivelse-Helsereform.md",
     "7-naringsliv-og-industri", "Legemiddelindustrien (LMI)"),
    ("2026-01-Apotekforeningens-innspill-til-Helsereformutvalget.md",
     "7-naringsliv-og-industri", "Apotekforeningen – løsninger"),
    ("2026-01-Framtidens-horselsomsorg-Audioplus-Norge-AS-Jorid-Lokken.md",
     "7-naringsliv-og-industri", "AudioPlus Norge AS"),
    ("2026-01-Innspill-helsereformutvalget-Apotekforeningen.md",
     "7-naringsliv-og-industri", "Apotekforeningen – utfordringer"),
    ("2026-01-Innspill-til-Helsereformutvalget-2026_Dignio.md",
     "7-naringsliv-og-industri", "Dignio"),
    ("2026-01-Innspill-til-Helsereformutvalget-fra-NHO.md",
     "7-naringsliv-og-industri", "NHO"),
    ("2026-01-Innspill-til-sekretariatsleder-helsereformutvalget.-RHF.-Spekter.md",
     "7-naringsliv-og-industri", "Spekter"),
    ("2026-01-Inspill-til-Helsereformutvalget-fra-Optikerbransjen.md",
     "7-naringsliv-og-industri", "Optikerbransjen – utfordringer"),
    ("2026-03-2026-03-26-Health2B-Innspill-til-Helsereformutvalget.md",
     "7-naringsliv-og-industri", "Health2B"),
    ("2026-03-Helsereformutvalget.-Horingsinnspill.-NHO-Geneo-Helse-og-velferd.md",
     "7-naringsliv-og-industri", "NHO Geneo"),
    ("2026-03-Sanofi-Innspill-til-helsereformutvalget.md",
     "7-naringsliv-og-industri", "Sanofi"),
    ("2026-03-TEK_Norge_Scenario-final.md",
     "7-naringsliv-og-industri", "TEK Norge"),
    ("2026-04-2026-04-Helsereformutvalget-Innspill-fra-Kernel.md",
     "7-naringsliv-og-industri", "Kernel"),
    ("2026-04-Helsereform-Novartis-innspill.md",
     "7-naringsliv-og-industri", "Novartis"),
    ("2026-04-Innspill-fra-Abelia-til-Helsereformutvalget.md",
     "7-naringsliv-og-industri", "Abelia"),
    ("2026-04-Innspill-fra-ressursgruppe-Value-Based-Healthcare-i-NHT.md",
     "7-naringsliv-og-industri", "Norway Health Tech – Value Based Healthcare"),
    ("2026-04-Innspill-fra-Roche-til-helsereformutvalget-14.04.26.md",
     "7-naringsliv-og-industri", "Roche Norge AS"),
    ("2026-04-Innspill-til-losninger-fra-Optikerbransjen-til-Helsereformutvalget.md",
     "7-naringsliv-og-industri", "Optikerbransjen – løsninger"),
    ("2026-05-Roche-Diagnostics-Norge-innspill-helsereformutvalget-2026.md",
     "7-naringsliv-og-industri", "Roche Diagnostics Norge"),
    ("2026-05-Simulering-som-nasjonal-strategi-SAFER-Laerdal.md",
     "7-naringsliv-og-industri", "Laerdal Medical"),
    ("2026-06-Innspill-til-Helsereformutvalget-fra-Topplederforum-Norway-Health-Tech.md",
     "7-naringsliv-og-industri", "Norway Health Tech – Topplederforum"),
]


def main():
    # Create category dirs
    for cat_dir in CATEGORIES:
        (MARKDOWN_DIR / cat_dir).mkdir(exist_ok=True)

    moved = 0
    missing = 0
    metadata: dict[str, list[str]] = {k: [] for k in CATEGORIES}

    for filename, cat_dir, org_name in FILE_MAP:
        src = MARKDOWN_DIR / filename
        if not src.exists():
            print(f"  MISSING  {filename}")
            missing += 1
            continue
        dst = MARKDOWN_DIR / cat_dir / filename
        shutil.move(str(src), str(dst))
        metadata[cat_dir].append(org_name)
        moved += 1

    # Any uncategorized files still in root?
    remaining = [f for f in MARKDOWN_DIR.iterdir()
                 if f.is_file() and f.suffix == ".md"]
    if remaining:
        print(f"\n⚠  {len(remaining)} uncategorized files remain in root:")
        for f in remaining:
            print(f"    {f.name}")

    # Write metadata markdown
    meta_path = MARKDOWN_DIR.parent / "innspill-kategorisert.md"
    lines = ["# Innspill kategorisert etter interessenttype\n"]
    for cat_dir, cat_label in CATEGORIES.items():
        orgs = metadata[cat_dir]
        lines.append(f"\n## {cat_label} ({len(orgs)} innspill)\n")
        for org in sorted(orgs):
            lines.append(f"- {org}")
    meta_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"\nDone: {moved} moved, {missing} missing")
    print(f"Metadata: {meta_path}")


if __name__ == "__main__":
    main()
